//CURRENT USER ACTIONS
export const GET_CURRENT_USER_PENDING = 'GET_CURRENT_USER_PENDING';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAILED = 'GET_CURRENT_USER_FAILED';

//lOG OUT ACTIONS
export const LOGOUT_USER = 'LOGOUT_USER';

//CURRENT USER ACTIONS
export const GET_ALL_LINKS_PENDING = 'GET_ALL_LINKS_PENDING';
export const GET_ALL_LINKS_SUCCESS = 'GET_ALL_LINKS_SUCCESS';
export const GET_ALL_LINKS_FAILED = 'GET_ALL_LINKS_FAILED';
export const ADD_LINK = 'ADD_LINK';